options:
  install_sources:
    type: string
    default: |
      - ppa:yellow/ppa
    description: (READ ONLY) apt source list line from where to get bundleservices deb.
  install_keys:
    type: string
    default: |
      - null
    description: (READ ONLY) List of keys to accept (none required for PPAs)
  listen-port:
    type: int
    default: 8000
    description: (READ ONLY) This is the tcp port on which the bundleservices server will listen for connections.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
         juju-myservice-0
      If you are running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup.
